/* TABLES */

CREATE TABLE AIR_LABEL
(
  BBL    VARCHAR2(10 BYTE)                      NOT NULL,
  LABEL  VARCHAR2(200 BYTE)                     NOT NULL,
  COUNT  INTEGER                                NOT NULL
);

CREATE INDEX AIR_BBL_IDX ON AIR_LABEL
(BBL);

CREATE TABLE CONDO_LABEL
(
  BBL    VARCHAR2(10 BYTE)                      NOT NULL,
  LABEL  VARCHAR2(200 BYTE)                     NOT NULL,
  COUNT  INTEGER                                NOT NULL
);

CREATE INDEX COND_BBL_IDX ON CONDO_LABEL
(BBL);

CREATE TABLE LOT_FACE_POINT
(
  SHAPE               MDSYS.SDO_GEOMETRY,
  TAX_LOT_FACE_TYPE   INTEGER,
  BBL                 VARCHAR2(10 BYTE),
  LENGTH              NUMBER(38,8),
  APPROX_LENGTH_FLAG  INTEGER,
  ANGLE               NUMBER(38,8),
  DELTA_X             NUMBER(38,8),
  DELTA_Y             NUMBER(38,8),
  BORO                NVARCHAR2(1),
  BLOCK               NUMBER(10),
  LOT                 NUMBER(5)
);

INSERT INTO USER_SDO_GEOM_METADATA SELECT 'LOT_FACE_POINT', 'SHAPE', DIMINFO, SRID FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'BOROUGH_POINT';

CREATE INDEX BBL_IDX ON LOT_FACE_POINT
(BBL);

CREATE INDEX LOT_FACE_POINT_SPATIAL_IDX ON LOT_FACE_POINT
(SHAPE)
INDEXTYPE IS MDSYS.SPATIAL_INDEX
PARAMETERS('layer_gtype=POINT');

CREATE TABLE SUB_LABEL
(
  BBL    VARCHAR2(10 BYTE)                      NOT NULL,
  LABEL  VARCHAR2(200 BYTE)                     NOT NULL,
  COUNT  INTEGER                                NOT NULL
);

CREATE INDEX SUB_BBL_IDX ON SUB_LABEL
(BBL);

CREATE TABLE TAX_BLOCK
(
  ID                NUMBER                      NOT NULL,
  BORO_BLOCK        VARCHAR2(6)               NOT NULL,
  BORO              VARCHAR2(1)                NOT NULL,
  BLOCK             VARCHAR2(10)                  NOT NULL,
  LABEL             VARCHAR2(25 BYTE)           NOT NULL,
  SHAPE             MDSYS.SDO_GEOMETRY,
  PRIMARY KEY(id)
);

INSERT INTO USER_SDO_GEOM_METADATA SELECT 'TAX_BLOCK', 'SHAPE', DIMINFO, SRID FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'BOROUGH_POINT';

CREATE UNIQUE INDEX TAX_BLOCK_BORO_BLOCK_IDX ON TAX_BLOCK(BORO_BLOCK);

CREATE INDEX TAX_BLOCK_SPATIAL_IDX ON TAX_BLOCK
(SHAPE)
INDEXTYPE IS MDSYS.SPATIAL_INDEX
PARAMETERS('layer_gtype=MULTIPOLYGON');

CREATE TABLE TAX_BLOCK_POINT
(
  BORO   NVARCHAR2(1)                           NOT NULL,
  BLOCK  NUMBER(10)                             NOT NULL,
  SHAPE  MDSYS.SDO_GEOMETRY
);

INSERT INTO USER_SDO_GEOM_METADATA SELECT 'TAX_BLOCK_POINT', 'SHAPE', DIMINFO, SRID FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'BOROUGH_POINT';

CREATE INDEX TAX_BLOCK_PT_SPATIAL_IDX ON TAX_BLOCK_POINT
(SHAPE)
INDEXTYPE IS MDSYS.SPATIAL_INDEX
PARAMETERS('layer_gtype=POINT');

CREATE TABLE TAX_LOT_AREA
(
  BBL       NVARCHAR2(10),
  LOT_AREA  NUMBER(19,1)
);

CREATE INDEX BBL_IDX_1 ON TAX_LOT_AREA
(BBL);

CREATE TABLE TAX_LOT_POINT
(
  BBL                VARCHAR2(10 BYTE)          NOT NULL,
  LOT                NUMBER(5)                  NOT NULL,
  AIR_RIGHTS_FLAG    CHAR(1 BYTE),
  CONDO_FLAG         CHAR(1 BYTE),
  REUC_FLAG          CHAR(1 BYTE),
  SUBTERRANEAN_FLAG  CHAR(1 BYTE),
  SHAPE              MDSYS.SDO_GEOMETRY,
  LOT_AREA           NUMBER(19,1)
);

INSERT INTO USER_SDO_GEOM_METADATA SELECT 'TAX_LOT_POINT', 'SHAPE', DIMINFO, SRID FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'BOROUGH_POINT';

CREATE INDEX TAX_LOT_POINT_IDX ON TAX_LOT_POINT
(BBL);

CREATE INDEX TAX_LOT_POINT_SPATIAL_IDX ON TAX_LOT_POINT
(SHAPE)
INDEXTYPE IS MDSYS.SPATIAL_INDEX
PARAMETERS('layer_gtype=POINT');

CREATE TABLE TAX_LOT_POLYGON_SDO
(
  OBJECTID                   INTEGER            NOT NULL,
  BORO                       NVARCHAR2(1)       NOT NULL,
  BLOCK                      NUMBER(10)         NOT NULL,
  LOT                        NUMBER(5)          NOT NULL,
  BBL                        NVARCHAR2(10),
  COMMUNITY_DISTRICT         NUMBER(5),
  REGULAR_LOT_INDICATOR      NVARCHAR2(1),
  NUMBER_LOT_SIDES           NUMBER(5),
  CONDO_FLAG                 NVARCHAR2(1),
  REUC_FLAG                  NVARCHAR2(1),
  AIR_RIGHTS_FLAG            NVARCHAR2(1),
  SUBTERRANEAN_FLAG          NVARCHAR2(1),
  EASEMENT_FLAG              NVARCHAR2(1),
  SECTION_NUMBER             NUMBER(5),
  VOLUME_NUMBER              NUMBER(5),
  PAGE_NUMBER                NVARCHAR2(15),
  LOT_NOTE                   NVARCHAR2(255),
  NYCMAP_BLDG_FLAG           NUMBER(5),
  MISSING_RPAD_FLAG          NUMBER(5),
  CONVERSION_EXCEPTION_FLAG  NUMBER(5),
  VALUE_REFLECTED_OUT_FLAG   NUMBER(5),
  CREATED_BY                 NVARCHAR2(50),
  CREATED_DATE               DATE,
  LAST_MODIFIED_BY           NVARCHAR2(50),
  LAST_MODIFIED_DATE         DATE,
  AV_CHANGE                  NUMBER(5),
  BW_CHANGE                  NUMBER(5),
  EFFECTIVE_TAX_YEAR         NVARCHAR2(50),
  BILL_BBL_FLAG              NUMBER(5),
  GLOBALID                   CHAR(38 BYTE)      NOT NULL,
  SHAPE                      MDSYS.SDO_GEOMETRY
);

INSERT INTO USER_SDO_GEOM_METADATA SELECT 'TAX_LOT_POLYGON_SDO', 'SHAPE', DIMINFO, SRID FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME = 'BOROUGH_POINT';

CREATE INDEX LOT_SDO_BBL_IDX ON TAX_LOT_POLYGON_SDO
(BBL);

CREATE INDEX LOT_SPATIDX ON TAX_LOT_POLYGON_SDO
(SHAPE)
INDEXTYPE IS MDSYS.SPATIAL_INDEX
PARAMETERS('layer_gtype=MULTIPOLYGON');

