CREATE OR REPLACE FORCE VIEW V_REUC_LOT
(
   OBJECTID,
   APPURTENANT_BORO,
   APPURTENANT_BLOCK,
   APPURTENANT_LOT,
   APPURTENANT_BBL,
   REUC_NUMBER,
   DELETED_FLAG,
   CREATED_BY,
   CREATED_DATE,
   LAST_MODIFIED_BY,
   LAST_MODIFIED_DATE,
   AV_CHANGE,
   BW_CHANGE,
   EFFECTIVE_TAX_YEAR,
   GLOBALID
)
AS
   SELECT "OBJECTID",
          "APPURTENANT_BORO",
          "APPURTENANT_BLOCK",
          "APPURTENANT_LOT",
          "APPURTENANT_BBL",
          "REUC_NUMBER",
          "DELETED_FLAG",
          "CREATED_BY",
          "CREATED_DATE",
          "LAST_MODIFIED_BY",
          "LAST_MODIFIED_DATE",
          "AV_CHANGE",
          "BW_CHANGE",
          "EFFECTIVE_TAX_YEAR",
          "GLOBALID"
     FROM REUC_LOTS
    WHERE deleted_flag = 0 OR deleted_flag IS NULL;
