set SRCSCHEMA=DOF_TAXMAP
set DESTSCHEMA=%SRCSCHEMA%
set SRCPASS=iluvesri247
set DESTPASS=iluvesri247365
set SRCDB=stgdb.xxx.zzz
set DESTDB=devdb
set TABLES=CONDO_LABEL,FINAL_ASMT,LOT_FACE_POINT,SUB_LABEL,TAX_BLOCK,TAX_BLOCK_POINT,TAX_LOT_POINT,TAX_LOT_POLYGON_SDO,TRANSPORTATION_STRUCTURE
set EXPFILE=D:\temp\dof_taxmap.dmp
echo starting export to %EXPFILE%
exp %SRCSCHEMA%/%SRCPASS%@%SRCDB% FILE=%EXPFILE% TABLES=(%TABLES%)
echo starting import from %EXPFILE%
imp %DESTSCHEMA%/%DESTPASS%@%DESTDB% FILE=%EXPFILE% TABLES=(%TABLES%) IGNORE=y
